// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/group/group.proto

package wm_sx_svc_group

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Group service

type GroupService interface {
	GetAllDiscussGroup(ctx context.Context, in *GetAllDiscussGroupRequest, opts ...client.CallOption) (*GetAllDiscussGroupResponse, error)
	JoinDiscussGroup(ctx context.Context, in *JoinDiscussGroupRequest, opts ...client.CallOption) (*JoinDiscussGroupResponse, error)
	CreateDiscussGroup(ctx context.Context, in *CreateDiscussGroupRequest, opts ...client.CallOption) (*CreateDiscussGroupResponse, error)
}

type groupService struct {
	c    client.Client
	name string
}

func NewGroupService(name string, c client.Client) GroupService {
	return &groupService{
		c:    c,
		name: name,
	}
}

func (c *groupService) GetAllDiscussGroup(ctx context.Context, in *GetAllDiscussGroupRequest, opts ...client.CallOption) (*GetAllDiscussGroupResponse, error) {
	req := c.c.NewRequest(c.name, "Group.GetAllDiscussGroup", in)
	out := new(GetAllDiscussGroupResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupService) JoinDiscussGroup(ctx context.Context, in *JoinDiscussGroupRequest, opts ...client.CallOption) (*JoinDiscussGroupResponse, error) {
	req := c.c.NewRequest(c.name, "Group.JoinDiscussGroup", in)
	out := new(JoinDiscussGroupResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupService) CreateDiscussGroup(ctx context.Context, in *CreateDiscussGroupRequest, opts ...client.CallOption) (*CreateDiscussGroupResponse, error) {
	req := c.c.NewRequest(c.name, "Group.CreateDiscussGroup", in)
	out := new(CreateDiscussGroupResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Group service

type GroupHandler interface {
	GetAllDiscussGroup(context.Context, *GetAllDiscussGroupRequest, *GetAllDiscussGroupResponse) error
	JoinDiscussGroup(context.Context, *JoinDiscussGroupRequest, *JoinDiscussGroupResponse) error
	CreateDiscussGroup(context.Context, *CreateDiscussGroupRequest, *CreateDiscussGroupResponse) error
}

func RegisterGroupHandler(s server.Server, hdlr GroupHandler, opts ...server.HandlerOption) error {
	type group interface {
		GetAllDiscussGroup(ctx context.Context, in *GetAllDiscussGroupRequest, out *GetAllDiscussGroupResponse) error
		JoinDiscussGroup(ctx context.Context, in *JoinDiscussGroupRequest, out *JoinDiscussGroupResponse) error
		CreateDiscussGroup(ctx context.Context, in *CreateDiscussGroupRequest, out *CreateDiscussGroupResponse) error
	}
	type Group struct {
		group
	}
	h := &groupHandler{hdlr}
	return s.Handle(s.NewHandler(&Group{h}, opts...))
}

type groupHandler struct {
	GroupHandler
}

func (h *groupHandler) GetAllDiscussGroup(ctx context.Context, in *GetAllDiscussGroupRequest, out *GetAllDiscussGroupResponse) error {
	return h.GroupHandler.GetAllDiscussGroup(ctx, in, out)
}

func (h *groupHandler) JoinDiscussGroup(ctx context.Context, in *JoinDiscussGroupRequest, out *JoinDiscussGroupResponse) error {
	return h.GroupHandler.JoinDiscussGroup(ctx, in, out)
}

func (h *groupHandler) CreateDiscussGroup(ctx context.Context, in *CreateDiscussGroupRequest, out *CreateDiscussGroupResponse) error {
	return h.GroupHandler.CreateDiscussGroup(ctx, in, out)
}
